import gzip
import os

html_source_path = os.path.join("data", "index.html")
header_output_path = os.path.join("src", "index_html.h")

os.makedirs(os.path.dirname(header_output_path), exist_ok=True)

print(f"Converting {html_source_path} to {header_output_path}")

with open(html_source_path, "rb") as f:
    html = f.read()

compressed = gzip.compress(html, compresslevel=9)

array_name = os.path.basename(html_source_path).replace(".", "_") # например, index_html
if html_source_path.startswith("data" + os.path.sep):
    array_name = "data_" + array_name # например, data_index_html

lines = []
for i in range(0, len(compressed), 16):
    chunk = compressed[i:i + 16]
    lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")

content = (
    "// Generated by tools/pre_build_html.py from data/index.html (gzip). Do not edit.\n"
    "#pragma once\n"
    "\n"
    f"const unsigned char {array_name}[] PROGMEM = {{\n"
    + "\n".join(lines)
    + "\n};\n"
    "\n"
    f"const unsigned int {array_name}_len = {len(compressed)};\n"
)

with open(header_output_path, "w", newline="\n") as f:
    f.write(content)

print(f"Gzipped {html_source_path}: {len(html)} -> {len(compressed)} bytes")
print(f"Modified {header_output_path} for PROGMEM.")
